/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.17
 * Generated at: 2023-05-19 06:03:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class List_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>실습 리스트</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	실습 리스트\r\n");
      out.write("	<hr>\r\n");
      out.write("	<details>\r\n");
      out.write("  		<summary>자작</summary>\r\n");
      out.write("  		<ul>\r\n");
      out.write("    			<li><a href=\"self/userlist.jsp\" target=\"_blank\">\r\n");
      out.write("				유저 정보 저장</a></li>\r\n");
      out.write("    			<li><a href=\"self/load.jsp\" target=\"_blank\">\r\n");
      out.write("				유저 정보 확인하기</a></li>\r\n");
      out.write("  		</ul>\r\n");
      out.write("	</details>\r\n");
      out.write("	<details>\r\n");
      out.write("		<summary>Chapter 03</summary>\r\n");
      out.write("  		<ul>\r\n");
      out.write("    		<li><a href=\"welcome.jsp\" target=\"_blank\">\r\n");
      out.write("			페이지 생성</a></li>\r\n");
      out.write("			<li><a href=\"insert_image.jsp\" target=\"_blank\">\r\n");
      out.write("			이미지 삽입하기</a></li>\r\n");
      out.write("			<li><a href=\"hyperlink_text.jsp\" target=\"_blank\">\r\n");
      out.write("			텍스트에 하이퍼링크</a></li>\r\n");
      out.write("			<li><a href=\"hyperlink_image.jsp\" target=\"_blank\">\r\n");
      out.write("			이미지에 하이퍼링크</a></li>\r\n");
      out.write("			<li><a href=\"table_default.jsp\" target=\"_blank\">\r\n");
      out.write("			테이블 만들기</a></li>\r\n");
      out.write("			<li><a href=\"table_option.jsp\" target=\"_blank\">\r\n");
      out.write("			테이블에 옵션 넣기</a></li>\r\n");
      out.write("  		</ul>\r\n");
      out.write("  	</details>\r\n");
      out.write("  	<details>\r\n");
      out.write("  		<summary>Chapter 04</summary>\r\n");
      out.write("  		<ul>\r\n");
      out.write("			<li>	<a href=\"ch04/form_login.jsp\" target=\"_blank\">\r\n");
      out.write("			폼태그 로그인</a></li>\r\n");
      out.write("			<li>	<a href=\"ch04/form_input.jsp\" target=\"_blank\">\r\n");
      out.write("			폼태그 개인정보 입력</a></li>\r\n");
      out.write("			<li>	<a href=\"ch04/form_element.jsp\" target=\"_blank\">\r\n");
      out.write("			엘레멘트 그룹 생성</a></li>\r\n");
      out.write("			<li>	<a href=\"ch04/form_select.jsp\" target=\"_blank\">\r\n");
      out.write("			콤보 박스 생성</a></li>\r\n");
      out.write("			<li>	<a href=\"ch04/form_optgroup.jsp\" target=\"_blank\">\r\n");
      out.write("			콤보 박스 옵션 그룹화</a></li>\r\n");
      out.write("			<li>	<a href=\"ch04/form_textarea.jsp\" target=\"_blank\">\r\n");
      out.write("			텍스트 영역 설정</a></li>\r\n");
      out.write("			<li>	<a href=\"ch04/form_membership01.jsp\" target=\"_blank\">\r\n");
      out.write("			회원가입 페이지</a></li>\r\n");
      out.write("			<li>	<a href=\"ch04/form_membership02.jsp\" target=\"_blank\">\r\n");
      out.write("			회원가입 완료 페이지</a></li>		\r\n");
      out.write("		</ul>\r\n");
      out.write("	</details>\r\n");
      out.write("  	<details>\r\n");
      out.write("  		<summary>Chapter 05</summary>\r\n");
      out.write("  		<ul>	\r\n");
      out.write("			<li>	<a href=\"ch05/handlerFunction.jsp\" target=\"_blank\">\r\n");
      out.write("			핸들러 함수</a></li>\r\n");
      out.write("			<li>	<a href=\"ch05/datainputCheck.jsp\" target=\"_blank\">\r\n");
      out.write("			데이터 입력 유뮤 체크</a></li>\r\n");
      out.write("			<li>	<a href=\"ch05/dataLength.jsp\" target=\"_blank\">\r\n");
      out.write("			입력 데이터의 길이 체크</a></li>\r\n");
      out.write("			<li>	<a href=\"ch05/dataLength_success.jsp\" target=\"_blank\">\r\n");
      out.write("			입력 데이터의 길이 체크 완료</a></li>\r\n");
      out.write("			<li>	<a href=\"ch05/isNaNcheck.jsp\" target=\"_blank\">\r\n");
      out.write("			데이터 유효성 검사</a></li>\r\n");
      out.write("			<li>	<a href=\"ch05/isNaNcheck_success.jsp\" target=\"_blank\">\r\n");
      out.write("			데이터 유효성 검사 완료</a></li>\r\n");
      out.write("			<li>	<a href=\"ch05/regularExpression.jsp\" target=\"_blank\">\r\n");
      out.write("			데이터 형식의 유효성 검사</a></li>\r\n");
      out.write("			<li>	<a href=\"ch05/regularExpression_success.jsp\" target=\"_blank\">\r\n");
      out.write("			데이터 형식의 유효성 검사 완료</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</details>\r\n");
      out.write("	<details>\r\n");
      out.write("		<summary>Chapter 06</summary>\r\n");
      out.write("		<ul>	\r\n");
      out.write("			<li>	<a href=\"ch06/sessionCreate.jsp\" target=\"_blank\">\r\n");
      out.write("			세션 제작 및 성공 여부 확인 (id=space, pw=123456)</a></li>\r\n");
      out.write("			<li>	<a href=\"ch06/sessionInfo_single.jsp\" target=\"_blank\">\r\n");
      out.write("			단일 세션 정보</a></li>\r\n");
      out.write("			<li>	<a href=\"ch06/sessionInfo_all.jsp\" target=\"_blank\">\r\n");
      out.write("			다중 세션 정보</a></li>\r\n");
      out.write("			<li>	<a href=\"ch06/sessionInterval.jsp\" target=\"_blank\">\r\n");
      out.write("			세션의 유효시간</a></li>\r\n");
      out.write("			<li>	<a href=\"ch06/sessionKeping.jsp\" target=\"_blank\">\r\n");
      out.write("			로그인 후 세션 유지 시간</a></li>\r\n");
      out.write("			<li>	<a href=\"ch06/sessionRemove.jsp\" target=\"_blank\">\r\n");
      out.write("			단일 세션 삭제</a></li>\r\n");
      out.write("			<li>	<a href=\"ch06/sessionRemove_all.jsp\" target=\"_blank\">\r\n");
      out.write("			다중 세션 삭제</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</details>\r\n");
      out.write("	<details>\r\n");
      out.write("		<summary>Chapter 07</summary>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch07/responseLoginform.jsp\" target=\"_blank\">\r\n");
      out.write("			response 내장 객체 (로그인 폼 화면)</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch07/responseLogin_process.jsp\" target=\"_blank\">\r\n");
      out.write("			response Redirection</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch07/responseLogin_success.jsp\" target=\"_blank\">\r\n");
      out.write("			로그인 성공</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch07/responseLogin_failure.jsp\" target=\"_blank\">\r\n");
      out.write("			로그인 실패</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch07/cookieLoginform.jsp\" target=\"_blank\">\r\n");
      out.write("			쿠키 로그인 폼</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch07/cookieLogin_process.jsp\" target=\"_blank\">\r\n");
      out.write("			쿠키 생성 및 로그인 성공</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch07/cookieLogin_failure.jsp\" target=\"_blank\">\r\n");
      out.write("			로그인 실패</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch07/cookieInformation.jsp\" target=\"_blank\">\r\n");
      out.write("			쿠키 객체 정보 확인하기</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch07/cookieRemove.jsp\" target=\"_blank\">\r\n");
      out.write("			쿠키 삭제</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</details>\r\n");
      out.write("	<details>\r\n");
      out.write("		<summary>Chapter 08</summary>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch08/forward.jsp\" target=\"_blank\">\r\n");
      out.write("			forward 액션태그</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch08/forward_process.jsp\" target=\"_blank\">\r\n");
      out.write("			forward로 부터 요청 받음</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch08/include.jsp\" target=\"_blank\">\r\n");
      out.write("			include 액션 태그</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch08/include_process.jsp\" target=\"_blank\">\r\n");
      out.write("			include_process.jsp 에서 수행한 명령</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch08/param.jsp\" target=\"_blank\">\r\n");
      out.write("			param 액션 태그</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch08/param_process.jsp\" target=\"_blank\">\r\n");
      out.write("			param 으로 부터 정보 전달 받음</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch08/useBeanDate.jsp\" target=\"_blank\">\r\n");
      out.write("			useBean 액션 태그</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</details>\r\n");
      out.write("	<details>\r\n");
      out.write("		<summary>Chapter 11</summary>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch11/dbConnTest.jsp\" target=\"_blank\">\r\n");
      out.write("			JDBC 커넥션</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch11/signup.jsp\" target=\"_blank\">\r\n");
      out.write("			회원가입</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch11/signup_process.jsp\" target=\"_blank\">\r\n");
      out.write("			회원가입 결과</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch11/membersList.jsp\" target=\"_blank\">\r\n");
      out.write("			가입자 명단</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch11/withdraw.jsp\" target=\"_blank\">\r\n");
      out.write("			회원탈퇴</a></li>\r\n");
      out.write("			<li>&nbsp;	<a href=\"ch11/withdraw_process.jsp\" target=\"_blank\">\r\n");
      out.write("			최원탈퇴 결과</a></li>\r\n");
      out.write("\r\n");
      out.write("		</ul>\r\n");
      out.write("	</details>\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
